#!/bin/sh

source_url() (
  echo http://www.haskell.org/ghc/dist/$1/ghc-$1-src.tar.bz2
)

binary_url() (
  case $_hsenv_private_host_os in
    linux)
      echo http://www.haskell.org/ghc/dist/$1/ghc-$1-x86_64-unknown-linux-deb7.tar.bz2
      return
      ;;
    darwin*)
      echo http://www.haskell.org/ghc/dist/$1/ghc-$1-x86_64-apple-darwin.tar.bz2
      return
      ;;
    mingw64)
      echo http://www.haskell.org/ghc/dist/$1/ghc-$1-x86_64-unknown-mingw32.tar.bz2
      return
      ;;
    mingw*)
      echo http://www.haskell.org/ghc/dist/$1/ghc-$1-i386-unknown-mingw32.tar.bz2
      return
      ;;
  esac
)

url_basename() (
  echo $1 | sed 's/#.*//' | sed 's/\?.*//' | sed 's%.*/%%'
)

has_command() (
  which $1 > /dev/null 2> /dev/null
)

downloader() (
  if has_command curl; then
    downloader_curl $1 $2
  elif has_command wget; then
    downloader_wget $1 $2
  elif has_command fetch; then
    downloader_fetch $1 $2
  elif has_command lwp-download; then
    downloader_lwp_download $1 $2
  else
    echo "curl/wget/fetch/lwp-download required"
    return 1
  fi
)

downloader_curl() (
  curl --fail --output $2 $1
)

downloader_wget() (
  wget --output-document=$2 $1
)

downloader_fetch() (
  fetch -o $2 $1
)

downloader_lwp_download() (
  lwp-download $1 $2
)
