#!/bin/sh

export HSENV_HOST_COMBO=`$HSENV_LIBEXEC_DIR/config.guess`
if [ "$HSENV_HOST_COMBO" != "" ]; then
  export HSENV_HOST_CPU=`echo $HSENV_HOST_COMBO | awk -F- '{print $1}'`
  export HSENV_HOST_VENDOR=`echo $HSENV_HOST_COMBO | awk -F- '{print $2}'`
  export HSENV_HOST_OS=`echo $HSENV_HOST_COMBO | awk -F- '{print $3}'`
else
  echo "host environment detection (config.guess) failed" >&$HSENV_RAW_STDERR
  exit 1
fi

is_mingw() (
  (echo $HSENV_HOST_OS | $HSENV_EGREP "^mingw" > /dev/null) \
    || (echo $HSENV_HOST_OS | $HSENV_EGREP "^msys" > /dev/null)
)
