#!/bin/sh

. $HSENV_LIBEXEC_DIR/init
cat <<USAGE >&$HSENV_RAW_STDOUT
usage: hsenv [FLAGS]

Flags:
--ghc=FILE          Use GHC from provided tarball
                    (e.g. ghc-7.0.4-i386-unknown-linux.tar.bz2)
                    (defaults to system's copy of GHC)
-h, --help          Show this help message
--make-cmd=CMD      Used as make substitute for installing GHC from tarball
                    (e.g. gmake)
                    (defaults to make)
--name=NAME         Use NAME as name of the Virtual Haskell Environment
                    (defaults to current directory name)
--no-ps1-indicator  Don't modify the shell prompt to indicate the current hsenv
-v, --verbose       Print some debugging info
--version           Show version string
--very-verbose      Print some more debugging info

Creates Virtual Haskell Environment in the current directory.
All files will be stored in the .hsenv[_NAME]/ subdirectory.

To activate a sandbox in the current directory, run:

    source .hsenv/bin/activate

To deactivate an active sandbox, run:

    deactivate_hsenv
USAGE
