#!/bin/sh

. $HSENV_LIBEXEC_DIR/init

filter_install() (
  CABAL_DIR=$HSENV_INSTALL_ROOT/cabal
  HACKAGE_CACHE=$HSENV_INSTALL_ROOT/cabal/packages
  mkdir -p $CABAL_DIR $HACKAGE_CACHE
  if is_mingw; then
    CABAL_DIR=`cd $CABAL_DIR && $COMSPEC /c cd | tr '\\\\' /`
    HACKAGE_CACHE=`cd $HACKAGE_CACHE && $COMSPEC /c cd | tr '\\\\' /`
    PATH_SEPARATOR=";"
  else
    PATH_SEPARATOR=:
  fi
  cat $1 \
    | sed "s|<HSENV>|$HSENV_WORK_DIR|g" \
    | sed "s|<HSENV_DIR>|$HSENV_INSTALL_ROOT|g" \
    | sed "s|<HSENV_NAME>|$HSENV_NAME|g" \
    | sed "s|<MODIFY_PS1>|$HSENV_PS1_INDICATOR|g" \
    | sed "s|<HACKAGE_CACHE>|$HACKAGE_CACHE|g" \
    | sed "s|<CABAL_DIR>|$CABAL_DIR|g" \
    | sed "s|<CABAL_CONFIG>|$CABAL_DIR/config|g" \
    | sed "s|<GHC_PACKAGE_PATH>|$hsenv_install_package_db|g" \
    | sed "s|<PATH_SEPARATOR>|$PATH_SEPARATOR|g" \
    > $2
)

install_helper_scripts() (
  default_bin=$HSENV_INSTALL_ROOT/bin
  cabal_bin=$HSENV_INSTALL_ROOT/cabal/bin

  mkdir -p $default_bin $cabal_bin
  echo $hsenv_install_package_db | tr -d '\r\n' > $HSENV_INSTALL_ROOT/ghc.package.conf.d.path
  path_var_prependix=$cabal_bin:$HSENV_INSTALL_ROOT/ghc/bin
  if is_mingw; then
    path_var_prependix=$path_var_prependix:$HSENV_INSTALL_ROOT/ghc/mingw/bin
  fi
  if $HSENV_BOOTSTRAP_CABAL; then
    path_var_prependix=$path_var_prependix:$HSENV_INSTALL_ROOT/cabal/bootstrap/bin
  fi
  filter_install $HSENV_SKELTON_DIR/cabal_config $HSENV_INSTALL_ROOT/cabal/config

  HSENV_BOOTSTRAP_CABAL=true
  if $HSENV_BOOTSTRAP_CABAL; then
    install_bootstrap_cabal
    if ! has_command $HSENV_INSTALL_ROOT/bootstrap/cabal/bin/cabal; then
      hsenv_warn Automated installation of \`cabal\' command was failed. Please install it manually if needed.
      hsenv_warn See \``log_file`\' for more information.
    fi
  fi

  mkdir -p $HSENV_INSTALL_ROOT/libexec
  if is_mingw; then
    $HSENV_INSTALL_ROOT/ghc/bin/ghc $HSENV_ROOT_DIR/exewrapper/src/Main.hs -o $HSENV_INSTALL_ROOT/libexec/shim
    cp $HSENV_INSTALL_ROOT/libexec/shim.exe $HSENV_INSTALL_ROOT/bin/cabal.exe
  else
    echo "#!$HSENV_INSTALL_ROOT/ghc/bin/runhaskell" >> $HSENV_INSTALL_ROOT/libexec/shim
    cat $HSENV_ROOT_DIR/exewrapper/src/Main.hs >> $HSENV_INSTALL_ROOT/libexec/shim
    chmod u+rx $HSENV_INSTALL_ROOT/libexec/shim
    ln -s $HSENV_INSTALL_ROOT/libexec/shim $HSENV_INSTALL_ROOT/bin/cabal
  fi
  $HSENV_INSTALL_ROOT/bin/cabal update | hsenv_debug -

  touch "$HSENV_INSTALL_ROOT/done"
  hsenv_info Done
)

install_bootstrap_cabal_mingw_archive() (
  version=$1
  hsenv_info Install: cabal-install-$version
  tmp_dir=$bootstrap_dir/tmp
  mkdir -p $tmp_dir
  url=http://www.haskell.org/cabal/release/cabal-install-$version/cabal-$version-i386-unknown-mingw32.tar.gz
  file=$tmp_dir/`url_basename $url`
  if ! downloader $url $file; then
    return 1
  fi
  extract_archive $file $bootstrap_dir/bin
)

install_bootstrap_cabal_mingw() (
  lib_version=$1
  if right_is_newer_or_same_version $lib_version 1.22; then
    install_bootstrap_cabal_mingw_archive 1.22.0.0
    return $?
  elif right_is_newer_or_same_version $lib_version 1.20; then
    install_bootstrap_cabal_mingw_archive 1.20.0.3
    return $?
  elif right_is_newer_or_same_version $lib_version 1.18; then
    version=1.18.0.3
  elif right_is_newer_or_same_version $lib_version 1.12; then
    version=0.14.0
  elif right_is_newer_or_same_version $lib_version 1.10; then
    version=0.10.2
  elif right_is_newer_or_same_version $lib_version 1.8; then
    version=0.8.2
  else
    version=0.6.4
  fi
  hsenv_info Install: cabal-install-$version
  downloader http://www.haskell.org/cabal/release/cabal-install-$version/cabal.exe $bootstrap_dir/bin/cabal.exe
)

install_bootstrap_cabal() (
  hsenv_info Bootstrap cabal-install
  cabal_dir=$HSENV_INSTALL_ROOT/cabal
  cabal_bootstrap_dir=$HSENV_INSTALL_ROOT/bootstrap/cabal
  mkdir -p $cabal_dir/bin
  mkdir -p $cabal_bootstrap_dir/bin
  lib_versions=`GHC_PACKAGE_PATH=$hsenv_install_package_db $HSENV_INSTALL_ROOT/ghc/bin/ghc-pkg field Cabal version`
  lib_version=`max_package_version $lib_versions`
  if [ -z "$lib_version" ]; then
    hsenv_warn Cabal package not found.
    return 1
  fi

  hsenv_info Found: Cabal-$lib_version
  if is_mingw; then
    install_bootstrap_cabal_mingw $lib_version
    return $?
  fi

  if right_is_newer_or_same_version $lib_version 1.22; then
    version=1.22.0.0
  elif right_is_newer_or_same_version $lib_version 1.20; then
    version=1.20.0.6
  elif right_is_newer_or_same_version $lib_version 1.18; then
    version=1.18.0.5
  elif right_is_newer_or_same_version $lib_version 1.16; then
    version=1.16.0.2
  elif right_is_newer_or_same_version $lib_version 1.12; then
    version=0.14.0
  elif right_is_newer_or_same_version $lib_version 1.10; then
    version=0.10.2
  elif right_is_newer_or_same_version $lib_version 1.8; then
    version=0.8.2
  elif right_is_newer_or_same_version $lib_version 1.6; then
    version=0.6.4
  elif right_is_newer_or_same_version $lib_version 1.4; then
    version=0.5.2
  else
    hsenv_info Automated installation of cabal-install is not supported
    return 0
  fi

  hsenv_info Install: cabal-install-$version

  patch_file=$HSENV_PATCH_DIR/cabal-install-$version.patch
  cabal_package_db=$HSENV_INSTALL_ROOT/cabal.package.conf.d
  cabal_bootstrap_package_db=$cabal_bootstrap_dir/package.conf.d
  hsenv_debug Cabal package db: $cabal_package_db
  hsenv_debug Bootstrap package db: $cabal_bootstrap_package_db
  ghc_version_output=`GHC_PACKAGE_PATH=$hsenv_install_package_db $HSENV_INSTALL_ROOT/ghc/bin/ghc-pkg --version`
  ghc_version=`ghc_pkg_version "$ghc_version_output"`
  if ! is_version $ghc_version; then
    hsenv_warn Couldn\'t extract ghc-pkg version number from: $ghc_version_output
    exit 1
  fi
  if [ `max_package_version 6.10.4 $ghc_version` = 6.10.4 ]; then
    hsenv_debug Detected GHC older than 6.12, initializing GHC_PACKAGE_PATH to file with '[]'
    echo "[]" > $cabal_package_db
    echo "[]" > $cabal_bootstrap_package_db
  else
    GHC_PACKAGE_PATH=$hsenv_install_package_db $HSENV_INSTALL_ROOT/ghc/bin/ghc-pkg init $cabal_package_db
    GHC_PACKAGE_PATH=$hsenv_install_package_db $HSENV_INSTALL_ROOT/ghc/bin/ghc-pkg init $cabal_bootstrap_package_db
  fi

  url=https://hackage.haskell.org/package/cabal-install-$version/cabal-install-$version.tar.gz
  cabal_install_archive=$HSENV_INSTALL_ROOT/cache/`url_basename $url`
  cabal_install_extracted=$HSENV_INSTALL_ROOT/tmp/cabal_bootstrap
  mkdir -p $HSENV_INSTALL_ROOT/cache $cabal_install_extracted
  downloader $url $cabal_install_archive \
    && extract_archive $cabal_install_archive $cabal_install_extracted \
    && cd $cabal_install_extracted \
    && (test ! -e $patch_file || patch < $patch_file >> `log_file`) \
    && chmod u+x bootstrap.sh \
    && hsenv_info Installing... \
    && ( \
      EXTRA_CONFIGURE_OPTS="--package-db=$cabal_bootstrap_package_db" \
      PREFIX=$cabal_bootstrap_dir \
      PATH=$path_var_prependix:$PATH \
      ./bootstrap.sh 2>&1 | $HSENV_PV | hsenv_debug -)
)

install_remote_url() (
  url=$1
  cache_dir=$HSENV_INSTALL_ROOT/cache
  file=$cache_dir/`url_basename $url`
  mkdir -p $cache_dir
  move_log_to_install_dir
  if ! downloader $url $file; then
    hsenv_abort Failed
  fi
  HSENV_GHC=$file
  install_local
)

install_with_version() (
  hsenv_info GHC version=$HSENV_GHC
  url=`binary_url $HSENV_HOST_COMBO $HSENV_GHC`
  if [ -z "$url" ]; then
    url=`source_url $HSENV_GHC`
  fi
  install_remote_url $url
)

install_remote() (
  install_remote_url $HSENV_GHC
)

install_local() (
  file=$HSENV_GHC
  if [ ! -f $file ]; then
    hsenv_abort Not found
  fi
  srcdir=$HSENV_INSTALL_ROOT/src
  move_log_to_install_dir
  hsenv_info Extracting...
  if ! extract_archive $file $srcdir; then
    hsenv_abort Failed
  fi
  hsenv_info Installing...
  if [ -f $srcdir/configure ]; then
    (cd $srcdir \
      && ./configure --prefix=$HSENV_INSTALL_ROOT/ghc \
      && ($HSENV_MAKE || true) \
      && $HSENV_MAKE install \
      && touch $HSENV_INSTALL_ROOT/ghc.done \
      ) 2>&1 | $HSENV_PV | hsenv_debug -
  else
    mv $srcdir $HSENV_INSTALL_ROOT/ghc && touch $HSENV_INSTALL_ROOT/ghc.done
  fi
  if [ ! -e $HSENV_INSTALL_ROOT/ghc.done ]; then
    hsenv_abort Failed
  fi
  if ! $HSENV_INSTALL_ROOT/ghc/bin/ghc --version > /dev/null; then
    hsenv_abort Failed
  fi

  hsenv_install_package_db=`$HSENV_INSTALL_ROOT/ghc/bin/ghc --print-global-package-db | tr '\\\\' /`
  if [ -z "$hsenv_install_package_db" ]; then
    hsenv_abort Failed
  fi

  install_helper_scripts
)

if [ -e "$HSENV_INSTALL_ROOT/done" ]; then
  hsenv_abort There is already installed hsenv \``basename $HSENV_INSTALL_ROOT`\' at $HSENV_WORK_DIR
elif [ -e "$HSENV_INSTALL_ROOT" ]; then
  rm -fr "$HSENV_INSTALL_ROOT"
fi

hsenv_info Install to $HSENV_INSTALL_ROOT
install_method=`installation_of $HSENV_GHC`
hsenv_debug Using \`$install_method\' method
$install_method
