#!/bin/sh

exec 5>&1
exec 6>&2
export HSENV_RAW_STDOUT=5
export HSENV_RAW_STDERR=6
export HSENV_WORK_DIR=`pwd`

. "`dirname $0`/../libexec/init"

start_new_log
read_option $*
hsenv_trace Options: "$@"
. $HSENV_COMMAND 2>&1 | hsenv_info -
