#!/bin/sh

exec 5>&1
exec 6>&2
export HSENV_RAW_STDOUT=5
export HSENV_RAW_STDERR=6
export HSENV_WORK_DIR=`pwd`

. "`dirname $0`/../libexec/init"

start_new_log
read_option $*
if [ -z "$HSENV_NAME" ]; then
  export HSENV_INSTALL_ROOT=$HSENV_WORK_DIR/.hsenv
else
  export HSENV_INSTALL_ROOT=$HSENV_WORK_DIR/.hsenv_$HSENV_NAME
fi
hsenv_trace Options: "$@"
. $HSENV_LIBEXEC_DIR/$HSENV_COMMAND 2>&1 | hsenv_info -
