#!/bin/sh

if [ -z "$HSENV_ROOT_DIR" ]; then
  export HSENV_ROOT_DIR=`cd "$(dirname $0)/.."; pwd`
fi
export HSENV_LIBEXEC_DIR="$HSENV_ROOT_DIR/libexec"
export HSENV_SKELTON_DIR="$HSENV_ROOT_DIR/skelton"
export HSENV_TMP_DIR="$HSENV_ROOT_DIR/tmp"
export HSENV_CACHE_DIR="$HSENV_TMP_DIR/cache"
export HSENV_EXTRACT_ARCHIVE_DIR="$HSENV_TMP_DIR/extract_archive"

. "$HSENV_LIBEXEC_DIR/log"
. "$HSENV_LIBEXEC_DIR/host"
. "$HSENV_LIBEXEC_DIR/option"
. "$HSENV_LIBEXEC_DIR/package"
. "$HSENV_LIBEXEC_DIR/downloader"
. "$HSENV_LIBEXEC_DIR/archive"
