#!/bin/sh

start_new_log() (
  mkdir -p `dirname $HSENV_EARLY_LOG_FILE`
  rm -f $HSENV_EARLY_LOG_FILE
  touch $HSENV_EARLY_LOG_FILE
)

move_log_to_install_dir() (
  mkdir -p $HSENV_INSTALL_ROOT
  if [ -f $HSENV_EARLY_LOG_FILE ]; then
    mv $HSENV_EARLY_LOG_FILE $HSENV_INSTALL_ROOT/hsenv.log
  fi
)

log_file() (
  if [ -z "$HSENV_WORK_DIR" ]; then
    echo Error: \$HSENV_WORK_DIR not defined
    exit 1
  fi

  if [ -f $HSENV_EARLY_LOG_FILE ]; then
    echo $HSENV_EARLY_LOG_FILE
    return
  fi

  if [ -z "$HSENV_INSTALL_ROOT" ]; then
    echo Error: \$HSENV_INSTALL_ROOT not defined
    exit 1
  fi

  echo $HSENV_INSTALL_ROOT/hsenv.log
)

hsenv_log() (
  log_level=$1
  shift

  if [ -z "$HSENV_LOG_LEVEL" ]; then
    return
  fi

  if [ "$*" = "-" ]; then
    while IFS= read line; do
      hsenv_log $log_level "$line"
    done
    return
  fi

  log_file=`log_file`
  echo "$*" >> $log_file

  if [ $log_level -le $HSENV_LOG_LEVEL ]; then
    if [ -t $HSENV_RAW_STDOUT ]; then
      echo "$*" >&$HSENV_RAW_STDOUT
    else
      echo "$*"
    fi
  fi
)

hsenv_trace() (
  hsenv_log 5 "$@"
)

hsenv_debug() (
  hsenv_log 4 "$@"
)

hsenv_info() (
  hsenv_log 3 "$@"
)

hsenv_warn() (
  hsenv_log 2 "$@"
)

hsenv_error() (
  hsenv_log 1 "$@"
)

hsenv_fatal() (
  hsenv_log 0 "$@"
)

hsenv_abort() { # No subshell
  hsenv_fatal "$@"
  hsenv_fatal See \``log_file`\' for more information
  exit 1
}
