#!/bin/sh

is_version() {
  echo $* | grep -E "^[0-9]+(\.[0-9]+)*$"
}

is_url() {
  echo $* | grep -E "^https?://.+$"
}

installation_of() {
  if [ -z "$1" ]; then
    echo transplant_local_executable
  elif [ $(is_version $1) ]; then
    echo install_remote_source
  elif [ $(is_url $1) ]; then
    echo install_remote_binary
  else
    echo install_local_binary
  fi
}
