#!/bin/sh

parse() {
  export HSENV_GHC=
  export HSENV_NAME=
  export HSENV_VERBOSE=0
  export HSENV_COMMAND=hsenv_main
  export HSENV_MAKE_COMMAND=make
  export HSENV_PS1_INDICATOR=true
  export HSENV_SANITY_CHECK=true
  export HSENV_SHARE_CABAL_CACHE=true
  export HSENV_BOOTSTRAP_CABAL=false

  for parsed_option in $*; do
    case $parsed_option in
      --ghc=*)
        HSENV_GHC=${parsed_option#*=}
        shift
        ;;
      --name=*)
        HSENV_NAME=${parsed_option#*=}
        shift
        ;;
      -v|--verbose)
        [ $HSENV_VERBOSE -lt 1 ] && HSENV_VERBOSE=1
        shift
        ;;
      --very-verbose)
        [ $HSENV_VERBOSE -lt 2 ] && HSENV_VERBOSE=2
        shift
        ;;
      --version)
        HSENV_COMMAND=hsenv_version
        return
        ;;
      -h|--help)
        HSENV_COMMAND=hsenv_help
        return
        ;;
      --dont-share-cabal-cache)
        HSENV_SHARE_CABAL_CACHE=false
        shift
        ;;
      --make-cmd=*)
        HSENV_MAKE_COMMAND=${parsed_option#*=}
        shift
        ;;
      --no-ps1-indicator)
        HSENV_PS1_INDICATOR=false
        shift
        ;;
      --skip-sanity-check)
        HSENV_SANITY_CHECK=false
        shift
        ;;
      --bootstrap-cabal)
        HSENV_BOOTSTRAP_CABAL=true
        shift
        ;;
      *)
        # unknown option
        ;;
    esac
  done
}

is_version() (
  echo $* | EGREP "^[0-9]+(\.[0-9]+)*$" > /dev/null
)

is_url() (
  echo $* | EGREP "^https?://.+$" > /dev/null
)

installation_of() (
  if [ -z "$1" ]; then
    echo transplant_local_executable
  elif is_version $1; then
    echo install_remote_source
  elif is_url $1; then
    echo install_remote_binary
  else
    echo install_local_binary
  fi
)
