#!/bin/sh

dependency_to_package_name() {
  dependency_to_package_name_and_space_and_version $1 | awk '{print $1}'
}

dependency_to_package_version() {
  dependency_to_package_name_and_space_and_version $1 | awk '{print $2}'
}

dependency_to_package_name_and_version() {
  dependency_to_package_name_and_space_and_version $1 | awk '{if ($2) { print $1"-"$2} else { print $1 }}'
}

dependency_to_package_name_and_space_and_version() {
  awk 'BEGIN {
    dep = ARGV[1]
    sub(/^builtin_/, "", dep)
    len = split(dep, dep_words, "-")
    printf dep_words[1]
    if (len == 1) {
      exit
    }
    for (a = 2; a <= len; a++) {
      dep_word = dep_words[a]
      split(dep_word, nums, ".")
      is_version = 1
      for (b = 1; b <= length(nums); b++) {
        num = nums[b]
        if (!match(num, /^[0-9]+$/)) {
          is_version = 0
          break
        }
      }
      if (is_version) {
        printf " " dep_word
        exit
      } else {
        printf "-" dep_word
      }
    }
  }' $1
}
